{
 "title": "Northwind Sample",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sales1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "تعداد کل سفارشات",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "select count(*) from Orders" }
     ]
    },
    {
     "title": "تعداد کل مشتریان",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(customer_id) AS \"CountOfCustomers\" FROM customers LIMIT 50 "
      }
     ]
    },
    {
     "title": "تعداد مشتریانی که خرید داشته اند",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(distinct customer_id) AS \"CountOfCustomers\" FROM orders LIMIT 50 "
      }
     ]
    },
    {
     "title": "تعداد محصولات",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "select count(*) from Products" }
     ]
    },
    {
     "title": "ده مشتری دارای بیشترین میزان خرید",
     "type": "barchart",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "select c.contact_name ,cast(sum((od.Quantity * od.unit_price ) - od.Discount) as int) as Price\r\nfrom order_details od \r\ninner join Orders o on o.order_id  = od.order_id \r\ninner join Customers c on c.customer_id  = o.customer_id \r\ngroup by c.contact_name \r\norder by Price desc\r\nlimit 10"
      }
     ]
    },
    {
     "title": "جمع مبلغ فروش به تفکیک روز",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 4 },
     "targets": [
      {
       "rawSql": "select o.order_date ,\r\ncast(sum((od.Quantity * od.unit_price ) - od.Discount) as int) as Price\r\nfrom Orders o\r\ninner join order_details od \r\non o.order_id  = od.order_id \r\ngroup by o.order_date ;"
      }
     ]
    },
    {
     "title": "پنج کشور دارای بیشترین مبلغ خرید",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select o.ship_country \r\n,sum((od.Quantity * od.unit_price) - od.Discount)::int as Price\r\nfrom Orders o\r\ninner join order_details od on od.order_id = o.order_id\r\ngroup by 1\r\norder by 2 desc\r\nlimit 5;"
      }
     ]
    },
    {
     "title": "پر فروشترین دسته بندی محصولات",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 12 },
     "targets": [
      {
       "rawSql": "select c.category_name ,\r\ncast(sum((od.Quantity * od.unit_price) - od.Discount) as int) as Price\r\nfrom order_details od\r\ninner join Products p on p.product_id  = od.product_id\r\ninner join Categories c on c.category_id  = p.category_id\r\ngroup by 1\r\norder by 2 desc;"
      }
     ]
    },
    {
     "title": "پنج کشور دارای بیشترین تعداد سفارش",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT ship_country, COUNT(order_id) AS \"CountOfOrders\" FROM orders GROUP BY ship_country ORDER BY COUNT(order_id) DESC LIMIT 5 "
      }
     ]
    }
   ]
  },
  { "title": "Sales2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "تعداد مشتریان",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "select count(*) from customers "
    }
   ]
  },
  {
   "title": "تعداد تامین کنندگان",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select count(*) from Suppliers" }
   ]
  },
  {
   "title": "تعداد شرکت های حمل و نقل",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select Count(*) from Shippers" }
   ]
  },
  {
   "title": "تعداد کارشناسان فروش",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct o.employee_id ) from orders o"
    }
   ]
  },
  {
   "title": "تعداد سفارش هر کارشناس فروش",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select concat('',e.first_name ,e.last_name ) as FullName,COUNT(o.order_id )\r\nfrom Orders o\r\ninner join Employees e\r\non e.employee_id  = o.employee_id \r\ngroup by concat('',e.first_name ,e.last_name )\r\norder by COUNT(o.order_id ) desc"
    }
   ]
  },
  {
   "title": "جمع مبلغ فروش هر کارشناس فروش",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "select concat('',e.first_name ,e.last_name ) as FullName,\r\ncast(sum((od.Quantity * od.unit_price ) - od.Discount) as int) as Price\r\nfrom Orders o\r\ninner join order_details od on od.order_id = o.order_id \r\ninner join Employees e on e.employee_id  = o.employee_id \r\ngroup by concat('',e.first_name ,e.last_name )\r\norder by sum((od.Quantity * od.unit_price) - od.Discount)::int desc"
    }
   ]
  },
  {
   "title": "جمع مبلغ سفارش و تعداد سفارش هر محصول",
   "type": "xychart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select p.product_name,COUNT(od.order_id) as Count_Of_Order,\r\nsum((od.Quantity * od.unit_price) - od.Discount)::int as Sum_Of_Order_Price\r\nfrom order_details od\r\ninner join Orders o on o.order_id = od.order_id\r\ninner join Customers c on c.customer_id = o.customer_id \r\ninner join products p on p.product_id = od.product_id \r\ngroup by p.product_name \r\norder by 2 desc,3 desc"
    }
   ]
  },
  {
   "title": "ده سفارش دارای بیشترین هزینه حمل",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "select o.customer_id ,SUM(o.Freight) as SumFreight \r\nfrom Orders o\r\ninner join Shippers s on s.shipper_id  = o.ship_via\r\ngroup by o.customer_id \r\norder by SumFreight desc\r\nlimit 10"
    }
   ]
  }
 ]
}